export const triggerStyles: React.CSSProperties = {
    position: 'absolute',
    top: '200px',
    insetInlineEnd: 'calc(40px* -1)',
    zIndex: '1',
    width: '40px',
    height: '40px',
    color: '#fff',
    fontSize: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#001529',
    borderStartStartRadius: '0',
    borderStartEndRadius: '6px',
    borderEndEndRadius: '6px',
    borderEndStartRadius: '0',
    cursor: 'pointer',
    transition: 'background 0.3s ease',
}
